language: python
sudo: required
virtualenv:
  system_site_packages: true
python:
  - "2.7"
before_install:
  - "sudo apt-add-repository -y ppa:reddit/ppa"
  - "sudo apt-get update -q"
  - "sudo apt-get install python-tinycss2 -y"
install: 
  - "pip install http://github.com/praw-dev/praw/tarball/d0f69dc84f70fc482ac5d6e707554853fd767e29#egg=praw"
  - "wget https://raw.githubusercontent.com/reddit/reddit/master/r2/r2/lib/cssfilter.py"
  - "wget https://raw.githubusercontent.com/reddit/reddit/master/r2/r2/lib/contrib/rcssmin.py"
# command to run tests
script: "python ./validatecss.py"
deploy:
  provider: script
  script: "python ./deploy.py"
  on:
    branch: master
