language: python
python:
  - "2.7"
install: 
  - "pip install -r requirements.txt"
  - "pip install tinycss2"
  - "wget https://raw.githubusercontent.com/reddit/reddit/master/r2/r2/lib/cssfilter.py"
  - "wget https://raw.githubusercontent.com/reddit/reddit/master/r2/r2/lib/contrib/rcssmin.py"
# command to run tests
script: "python ./validatecss.py"
